services:  
  db:
    image: mysql:8.0.27
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306" 
    volumes:
      - ./db:/docker-entrypoint-initdb.d:rw
    networks:
      - default

  backend:
    build: backend
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    depends_on:
      - db 
    networks:
      - default

  frontend:
    build: frontend
    container_name: react-app
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - default